apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-name" . }}-config
data:
  zabbix_server_name: {{ .Values.config.zabbixServerName }}
  zabbix_debug: |
    <?php print_r($_SERVER["HOSTNAME"]); ?>
  zabbix.conf.php: |
    <?php
    $DB['TYPE'] = 'MYSQL';
    $DB['SERVER'] = {{ include "zabbix-mariadb-chart.dbServer" . }};  # Dynamically resolves to "<release-name>-mariadb"
    $DB['PORT'] = getenv('DB_PORT') ?: '{{ .Values.config.dbPort }}';
    $DB['DATABASE'] = getenv('DB_DATABASE') ?: 'zabbix';
    $DB['USER'] = getenv('DB_USER') ?: 'zabbix';
    $DB['PASSWORD'] = getenv('DB_PASSWORD') ?: 'zabbix';
    $DB['SCHEMA'] = '';
    $ZBX_SERVER = getenv('ZABBIX_SERVER') ?: 'zabbix-server';
    $ZBX_SERVER_PORT = getenv('ZABBIX_SERVER_PORT') ?: '{{ .Values.config.zabbixServerPort }}';
    $ZBX_SERVER_NAME = 'KUBERNETES_POD_HOSTNAME';
    $IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;
  zabbix_server.conf: |
    LogType=console
    ListenIP=0.0.0.0
    ListenPort=9997
    DebugLevel=0
    DBHost={{ include "zabbix-mariadb-chart.dbServer" . }}  # Dynamically resolves to "<release-name>-mariadb"
    DBName=zabbix
    DBUser=zabbix
    DBPassword=${MARIADB_PASSWORD}
    StartPollers=10
    StartPreprocessors=10
    StartPollersUnreachable=10
    StartPingers=10
    StartDiscoverers=10
    StartHTTPPollers=10
    StartTimers=10
    StartAlerters=10
    CacheSize=500M
    StartDBSyncers=4
    HistoryCacheSize=160M
    HistoryIndexCacheSize=114M
    TrendCacheSize=114M
    Timeout=4
    LogSlowQueries=3000
    StartLLDProcessors=10
    StatsAllowedIP=127.0.0.1
    StartReportWriters=2
    WebServiceURL=http://zabbix_web_service:9998/report