apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart-name" . }}-kubectl-executor-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "chart-name" . }}-kubectl-executor
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "chart-name" . }}-kubectl-executor-role
  apiGroup: rbac.authorization.k8s.io