apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-name" . }}-db-secret
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.secrets.mariadbRootPassword }}
  MARIADB_DATABASE: {{ .Values.secrets.mariadbDatabase }}
  MARIADB_USER: {{ .Values.secrets.mariadbUser }}
  MARIADB_PASSWORD: {{ .Values.secrets.mariadbPassword }}