apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-name" . }}-mariadb
  labels:
    app: {{ include "chart-name" . }}-mariadb
spec:
  selector:
    app: {{ include "chart-name" . }}-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP