name: Publish Helm Charts

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Helm CLI
      - name: Set up Helm CLI
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      # Step 3: Package Helm charts
      - name: Package Helm Charts
        run: |
          mkdir -p charts/packaged
          for chart in charts/*/Chart.yaml; do
            helm package "$(dirname "$chart")" --destination charts/packaged
          done

      # Step 4: Generate index.yaml
      - name: Generate index.yaml
        run: |
          helm repo index charts/packaged --url https://maborak-technologies-inc.github.io/helm

      # Step 5: Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: charts/packaged
          publish_branch: gh-pages