name: Publish Helm Charts

on:
  push:
    branches:
      - main # Trigger the workflow when you push changes to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Helm CLI
      - name: Set up Helm CLI
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0 # Replace with the desired Helm version

      # Step 3: Package Helm charts
      - name: Package Helm Charts
        run: |
          mkdir -p packaged
          for chart in */Chart.yaml; do
            helm package "$(dirname "$chart")" --destination packaged
          done

      # Step 4: Generate or update index.yaml
      - name: Update index.yaml
        run: |
          helm repo index packaged --url https://maborak-technologies-inc.github.io/helm
          mv packaged/* .

      # Step 5: Deploy to GitHub Pages
      - name: Commit and push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Deploy everything in the current directory to gh-pages
          publish_branch: gh-pages
